routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


Auth::routes();
Route::group(['middleware' => ['guest', 'disablepreventback']], function()
{
    //  Route::get('/', function () {
    //     return view('underMaintainance');
    // });

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/login', function () {
        return view('welcome');
    });

    Route::get('/register', function () {
        return view('welcome');
    });

    //ForgotPassword
    Route::get('/forgotPassword', function () {
        return view('forgotPassword');
    });

    Route::post('emailToResetPswd','Forgot_PasswordController@forgotPassword');

    //Reset password
    Route::get('/resetPasswordForm', function () {
        return view('resetPassword');
    });
    Route:: post('resetPassword', 'Forgot_PasswordController@resetPassword');


});

Route::get('dcmRedirect', function () {
    return view('dcmRedirect');
});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('getErrorExcelFIle/{Camp_ID}' , 'CampaignPublishercontroller@getErrorExcelFIle');
Route::get('getErrorExcelFIleCount' , 'CampaignPublishercontroller@getErrorExcelFIleCount');




Route::get('getLocationSheet' , 'CampaignPublishercontroller@getLocationSheet');

Route::get('alwaysOnCampaignDetails/{adamUniqueKey}/{id}' , 'AdamSheetController@alwaysOnCampaignDetails');

// ------------------------------------------------------------------------------------------
Route::group(['middleware' =>['auth','user_role']], function()
{
    Route::get('home', 'HomeController@index');
    Route::resource('/Campaign','CampaignController');
   //   Route::resource('/Campaign', [ 'middleware' => ['user_role'], 'uses' =>'CampaignController']);



    //Person routes starts
    Route::get('Person', 'PersonController@index');
    Route::post('person', 'PersonController@savePerson')->name('savePerson');
    Route::post('editPerson', 'PersonController@editPerson')->name('editPerson');
    Route::get('person/delete/{id}', 'PersonController@deletePerson')->name('PersonDelete');
    //person routes ends
    //card route
    Route::get('Card', 'cardController@index');
    Route::post('Card', 'cardController@saveCard')->name('saveCard');
    Route::post('editCard', 'cardController@editCard')->name('editCard');
    Route::get('card/delete/{id}', 'cardController@deleteCard')->name('CardDelete');
    Route::post('addCreative', 'cardController@addCreative')->name('addCreative');




    // Route::post('person', 'PersonController@savePerson')->name('savePerson');
    // Route::post('editPerson', 'PersonController@editPerson')->name('editPerson');
    // Route::get('person/delete/{id}', 'PersonController@deletePerson')->name('PersonDelete');
    //end of card route
    Route::post('/selectBrandClient','CampaignController@selectBrand');
    //CRUD:Publisher
    Route::resource('/Publisher','PublisherController');

    //CRUD:Client
    Route::resource('/Client','ClientController');
    // get Client login credentials
    Route::get('/CredentialsClient/{client_id}', ['as' => 'Client.credentials','uses' =>'ClientController@getClientCredentials']);
     // update Client login credentials
    Route::post('/saveClientCredentials/{client_id}', ['as' => 'Client.saveClientCredentials','uses' =>'ClientController@saveClientCredentials']);
    // ---------------------------------------------------------------------------------------
    // get publisher login credentials
    Route::get('/Credentials/{p_id}', ['as' => 'Publisher.credentials','uses' =>'PublisherController@getCredentials']);
    // update publisher login credentials
    Route::post('/saveCredentials/{p_id}', ['as' => 'Publisher.saveCredentials','uses' =>'PublisherController@saveCredentials']);
    // ---------------------------------------------------------------------------------------

    //View: All Brand
    Route::get('/ClientBrand/{c_id}', ['as' => 'ClientBrand.getAllBrandsToDisplay',
								  'uses' =>'ClientBrandController@getAllBrandsToDisplay']);
    // ---------------------------------------------------------------------------------------
    //Create:  Brand
    Route::get('/ClientBrand/ClientBrand/{c_id}', [ 'as' => 'ClientBrand.createBrand',
     								  			    'uses' =>'ClientBrandController@createBrand']);
    //Store:  Brand
    Route::post('/ClientBrand/storeBrand', [ 'as' => 'ClientBrand.storeBrand',
 								  			    'uses' =>'ClientBrandController@storeBrand']);
    //edit:  Brand
    Route::get('/ClientBrand/editBrand/{b_id}/{c_id}', [ 'as' => 'ClientBrand.editBrand',
 								  			    'uses' =>'ClientBrandController@editBrand']);
    //update:  Brand
    Route::patch('/ClientBrand/updateBrand/{b_id}/{c_id}', [ 'as' => 'ClientBrand.updateBrand',
 								  			    'uses' =>'ClientBrandController@updateBrand']);
    //delete:  Brand
    Route::delete('/ClientBrand/destroyBrand/{b_id}/{c_id}', [ 'as' => 'ClientBrand.destroyBrand',
 								  			    'uses' =>'ClientBrandController@destroyBrand']);
    // ---------------------------------------------------------------------------------------

    // ---------------------------------------------------------------------------------------
    //Excel sheet
    Route::get('DownloadLineItemExcelSheet', 'CampaignPublishercontroller@getCampaignExcel')->name('downloadlineitemexcel');
    Route::get('getErrorExcelFIle' , 'CampaignPublishercontroller@getErrorExcelFIle');
    Route::post('UploadInputLineExcel/{id}/{cid}', 'CampaignPublishercontroller@ExcelSheetUpload')->name('UploadLineItemExcel');
    //end ExcelSheet
    // ---------------------------------------------------------------------------------------


    // Route::get('/api', function () {
    //     return view('api');
    // });

    Route::get('/api','AdamAPIController@apiView');


    // =============adamAPI=========================================
        
    Route::post('/fbAPI','AdamAPIController@fbAPIProcessing');

    Route::get('/dbmBasic', 'AdamAPIController@dbmBasic');
    Route::get('/dbmAPI', 'AdamAPIController@dbmAPI');
    Route::get('/dbmCron', 'AdamAPIController@dbmCron');
    Route::get('/oauth2CallBackDBM', 'AdamAPIController@oauth2CallBackDBM');
    
    Route::post('/adamDcm', 'AdamAPIController@adamDcm');
    Route::post('/adamAdwords','AdamAPIController@adamAdwords');

    Route::post('/testAdamSizMek', 'AdamAPIController@testAdamSizMek');
    //Route::get('/oauth2CallBackDBM', [ 'as' => 'oauth2CallBackDBM',
    //                                            'uses' =>'AdamAPIController@oauth2CallBackDBM']);

    Route:: post('/saveLineItemAdsetMapValue', 'AdamSheetController@saveLineItemAdsetMapValue');

    Route::get('/adamPublisherHome','AdamPublisherController@getCompaignDetails');

    
    Route::get('/adamPublihserAdamLine/{Campaign_ID}/{PublisherId}', ['as' => 'adamPublihser.adamPublihserAdamLine','uses' =>'AdamPublisherController@AdamPublisherAllAdamLines']);

    Route::get('/adamPublihserAdamLine/{AdamsLineItem_ID}', ['as' => 'adamPublihser.adamPublihserAdamLineDaily','uses' =>'AdamPublisherController@AdamPublisherAdamLinesDailyData']);

    Route::post('/saveDailyAdamLineItems', 'AdamPublisherController@saveDailyAdamLineItems');

    Route::post('/adamBingAdsApi','AdamAPIController@adamBingAdsApi');

    Route::post('/AdamTaboola','AdamAPIController@AdamTaboola');
    Route::post('/AdamOutbrain','AdamAPIController@AdamOutbrain');

    Route::get('/adamGoogleAnalytics', 'AdamAPIController@adamGoogleAnalytics');
     Route::get('/oauth2CallBackGoogleAnalytics', 'AdamAPIController@oauth2CallBackGoogleAnalytics');



    Route::post('/uploadExcelForManualPublisher', 'AdamManualPublisherUploadController@UploadExcelForManualPublisher')->name('uploadExcelForManualPublisher');
    Route::post('/getManualPublisherExcelInputFile', 'AdamSheetController@getManualPublisherExcelInputFile');

    Route::get('/deleteManulReport/{manualReportId}', 'AdamSheetController@deleteManulReport');

    Route::post('/getAdamLineItem_URLMapping', 'AdamSheetController@getAdamLineItem_URLMapping');
    Route::post('/upload_URL_ForManualPublisher', 'AdamManualPublisherUploadController@upload_URL_ForManualPublisher')->name('upload_URL_ForManualPublisher');

    Route::post('/hotstar','AdamAPIController@hotstar');
    // =============End adamAPI=======================================
    Route::post('/dailyProgrssCheck','AdamAPIController@dailyProgrssCheck');
    Route::post('/getProgressStatus','AdamAPIController@getProgressStatus');
    Route::post('/fbApis','ApiController@addFbApi');
    Route::post('/bingAdsApi','ApiController@addBingAdsApi');
    Route::resource('/unzip', 'ApiController@extractKeyZip');
    Route::post('/taboolaApi','ApiController@addTaboolaApi');
    Route::resource('/dcmApi', 'ApiController@addDcmApi');
    Route::resource('/dcmRedirectApi', 'ApiController@dcmRedirectApi');
    Route::post('/outBrainApi', 'ApiController@addOutbrainApi');
    Route::post('/adWordsApi', 'ApiController@addAdWordsApi');
    Route::get('/getTaboolaResult', function () {
        return view('getTaboolaResult');
    });
    Route::get('/getOutBrainResult', function () {
        return view('getOutBrainResult');
    });

    Route::post('/addSizMek', 'ApiController@addSizMek');
    Route::post('/testSizMek', 'ApiController@testSizMek');
    
    Route::post('/addCityBank', 'ApiController@addCityBank');
    Route::post('/addGoogleAnalytics', 'ApiController@addGoogleAnalytics');
    
    Route::get('/addGoogleAnalytics', 'ApiController@addGoogleAnalytics');

app/Publisher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Publisher extends Model
{

	public $timestamps = false;

    protected $primaryKey = 'id';

    public $fillable = ['PublisherName','Genre_ID','PublisherType_ID','CreatedOn','ModifiedOn','ModifiedBy','isActive'];

	public $table = "dbo.Publisher";

}

app/PublisherType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PublisherType extends Model
{

	public $timestamps = false;

    protected $primaryKey = 'id';

    public $fillable = ['PublisherTypeName','CreatedOn','ModifiedOn','ModifiedBy','isActive'];

	public $table = "dbo.PublisherType";

}

resources/views/Publisher/Credentials.blade.php
@extends('layouts.appResourcePublisher')
 <div class="container">
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Log-In Credentials For :</h2>
                <h4>Publisher Name : {{$PublisherName}}</h4>
            </div>
        </div>
    
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    
    {!! Form::open(['method' => 'post','route' => ['Publisher.saveCredentials', $p_id]]) !!} 

       <div class="row col-md-3"> 
		  <div class="col-xs-12 col-sm-12 col-md-12">
		  <div class="form-group"><strong>User Name:</strong></div>
		    <div class="form-group">
		        {!! Form::email('UserName', $UserName, array('placeholder' => 'User name','class' => 'form-control','required'=>'')) !!}
		      </div>
		  </div> 
 
		  <div class="col-xs-12 col-sm-12 col-md-12">
		    <div class="form-group"><strong>Password:</strong></div>
		    <div class="form-group"> 
		       
		      {!! Form::text('Password', $Password, array('placeholder' => 'Password','class' => 'form-control','required'=>'')) !!}
		 
		    </div>
		</div>    
		<div class="col-xs-12 col-sm-12 col-md-12">    
    		<input type="hidden" name="_token" value="{{ csrf_token() }}">
    		<div class="col-xs-12 col-sm-12 col-md-12 text-center">
      			<button type="submit" class="btn btn-primary pull-left">Save</button>
      			<div class="pull-left" style="padding-left:20px;">
          			<a class="btn btn-primary" href="{{ route('Publisher.index') }}"> Back</a>
      			</div>
    		</div>
  		</div>



     {!! Form::close() !!}
	 
	</div>
@endsection
</div>

resources/views/Publisher/create.blade.php
@extends('layouts.appResourcePublisher')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Create Publisher</h2>
            </div>
        </div>
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {!! Form::open(array('route' =>'Publisher.store','method'=>'POST')) !!}
         @include('Publisher.form')
    {!! Form::close() !!}
	</div>
	
@endsection

resources/views/Publisher/edit.blade.php
@extends('layouts.appResource')
 <div class="container">
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Update Publisher</h2>
            </div>
           
        </div>
    
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
     {!! Form::model($getGenre,['method' => 'PATCH','route' => ['Publisher.update', 
    $id]]) !!} 
        @include('Publisher.form')
     {!! Form::close() !!}
	 
	</div>
@endsection
</div>

resources/views/Publisher/form.blade.php
<div class="row col-md-3">
	
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group"><strong>Publisher Name:</strong></div>
    <div class="form-group">
        {!! Form::text('PublisherName', $PublisherName, array('placeholder' => 'Publisher name','class' => 'form-control','required'=>'', 'maxlength'=>'50')) !!}
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group"><strong>Genre :</strong></div>
      <div class="form-group col-xs-13 col-sm-13 col-md-13">
          <select class="form-control" name="Genre_ID" id="Genre_ID" data-parsley-required="true">
            @foreach ($getGenre as $getGenre_val) 
            {
              <option value="{{ $getGenre_val->id }}" 
                {{$selectGenreID == $getGenre_val->id ? 'selected="selected"' : '' }}>
                {{ $getGenre_val->GenreName }}
              </option>  
            }
            @endforeach
          </select>
      </div>  
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group"><strong>Publisher Type :</strong></div>
    <div class="form-group col-xs-13 col-sm-13 col-md-13">
        <select class="form-control" name="PublisherType_ID" id="PublisherType_ID" data-parsley-required="true">
          @foreach ($getPublisherType as $getPublisherType) 
          {
            <option value="{{ $getPublisherType->id }}" 

              {{$PublisherType_ID == $getPublisherType->id ? 'selected="selected"' : '' }}>
              {{ $getPublisherType->PublisherTypeName }}
            </option>  
          }
          @endforeach
        </select>
    </div>  
  </div>
 
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">    
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
      <button type="submit" class="btn btn-primary pull-left">Save</button>
      <div class="pull-left" style="padding-left:20px;">
          <a class="btn btn-primary" href="{{ route('Publisher.index') }}"> Back</a>
      </div>
    </div>
  </div>
</div>

resources/views/Publisher/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="pull-left"><h2>Publisher Details</h2></div>
            <div class="pull-right margin-top-20">
                <a class="btn btn-success" href="{{route('Publisher.create') }}">Create Publisher </a>
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <div class="portlet-body">
        <div class="table-toolbar">
            <div style="width: 100%; overflow-x:auto;margin-bottom: 50px;">
                <table class="table table-bordered display" id="sample_editable_1">
                    <thead> 
                        <tr>
                            <th>Publisher Name</th>
                            <th>Genre Name</th>
                            <th>Publisher Type</th>
                            <th width="280px">Action</th>
                        </tr>
                    </thead> 
                    <tbody> 
                       @foreach ($Publisherdetails_index as $Publisherdetails_index_data)
                        <tr align="center">
                            <td>{{$Publisherdetails_index_data->PublisherName}}</td>
                            <td>{{$Publisherdetails_index_data->GenreName}}</td>
                            <td>{{$Publisherdetails_index_data->PublisherTypeName}}</td>
                            <td>
                               <a class="btn btn-primary" href="{{ route('Publisher.edit',$Publisherdetails_index_data->id) }}">Edit</a>

                               <a class="btn btn-primary" href="{{route('Publisher.credentials',['publisherId'=>$Publisherdetails_index_data->id])}}">Credentials</a> 
                              
                               {!! Form::open(['method' => 'DELETE','route' => ['Publisher.destroy',$Publisherdetails_index_data->id],'style'=>'display:inline']) !!}
                               {!! Form::submit('Delete', ['class' => 'btn btn-danger', 'onclick'=>'return confirm("Are you sure you want to delete?")']) !!}
                               {!! Form::close() !!}


                                 

                            </td>
                        </tr>
                       @endforeach
                    </tbody>
                </table>
            @endsection
        </div>
    </div>
</div>

resources/views/Publisher/show.blade.php
@extends('layouts.app')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Show Type Of Work</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('Publisher.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Work Type:</strong>
                {{ $workshow->work}}
            </div>
        </div>
        
    </div>
@endsection